# Generated by Django 4.1.1 on 2022-10-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='semester',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], help_text='only applicable to student', null=True),
        ),
    ]
