# Generated by Django 4.1.1 on 2022-10-16 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningAttendance', '0002_initial'),
        ('users', '0004_alter_customuser_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='course',
            field=models.ForeignKey(blank=True, help_text='only applicable to student', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='learningAttendance.course', verbose_name='Student Course'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='school',
            field=models.ForeignKey(blank=True, help_text='only applicable to student', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='learningAttendance.school', verbose_name='Student Faculty'),
        ),
    ]
