# Generated by Django 4.1.1 on 2022-10-16 15:18

from django.db import migrations, models
import django.db.models.deletion
import learningAttendance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to=learningAttendance.models.save_course_image, verbose_name='course image')),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.PositiveSmallIntegerField(verbose_name='Chapter no.')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('video', models.FileField(blank=True, upload_to=learningAttendance.models.save_lecture_files, verbose_name='video')),
                ('ppt', models.FileField(blank=True, null=True, upload_to=learningAttendance.models.save_lecture_files, verbose_name='presentation')),
                ('notes', models.FileField(blank=True, null=True, upload_to=learningAttendance.models.save_lecture_files, verbose_name='notes')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to=learningAttendance.models.save_school_image, verbose_name='school image')),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('year', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('image', models.ImageField(blank=True, upload_to=learningAttendance.models.save_unit_image, verbose_name='unit image')),
                ('is_offered', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='learningAttendance.course')),
            ],
        ),
    ]
