# Generated by Django 4.1.1 on 2022-10-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningAttendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='attendance_marked',
            field=models.BooleanField(default=False),
        ),
    ]
