# Generated by Django 4.1.1 on 2022-11-06 17:14

from django.db import migrations, models
import django.db.models.deletion
import learningAttendance.models


class Migration(migrations.Migration):

    dependencies = [
        ('learningAttendance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_pdf', models.FileField(blank=True, upload_to=learningAttendance.models.course_unit_pdf, verbose_name='Unit PDF')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='learningAttendance.course')),
            ],
        ),
    ]
