# Generated by Django 4.1.1 on 2022-11-06 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learningAttendance', '0003_courseunits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='school',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Lecturer'),
        ),
    ]
